{% set version = SDRPLAY_API_VERSION %}

{% set urlbase = "https://www.sdrplay.com/software/" %}

package:
  name: sdrplay_api
  version: {{ version }}

source:
  url: {{ urlbase }}SDRplay_RSP_API-Linux-{{ version }}.run  # [linux64]
  sha256: aefe8733cba3e480157c28439c1ed5ab757724a7a26fe74eee92cda6f36145a8  # [linux64]

  url: {{ urlbase }}SDRplay_RSP_API-ARM64-{{ version }}.run  # [aarch64]
  sha256: 1893c55ba5bc29ee269dccdc48b1587e2a0e30609f167dbf108034ed59e65466  # [aarch64]

  url: {{ urlbase }}SDRplayAPI-macos-installer-universal-{{ version }}.pkg  # [osx]
  sha256: 964f39158db2624f5b88cbe2407a4613841eba2c981312eed106a4dfcb1d60fc  # [osx]

  url: {{ urlbase }}SDRplay_RSP_API-Windows-{{ version }}.exe  # [win]
  sha256: e76a76ed7281485e2680e590ff6fd48f0d75b73b690198d7f6df284ebc613477  # [win]
  fn: sdrplay_api.exe  # [win]

  no_hoist: true
  folder: binary

build:
  number: 0
  run_exports:
    weak_constrains:
      - {{ pin_subpackage('sdrplay_api', exact=True) }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - m2-sed  # [win]
    - sed  # [not win]
  host:
    - libudev  # [linux64]
    - libusb
  run:
    - curl *
    - p7zip  # [unix]

test:
  commands:
    # verify that libraries get installed
    - test -f $SDRPLAY_PREFIX/lib/libsdrplay_api.so  # [unix]
    - if not exist %SDRPLAY_PREFIX%\\bin\\sdrplay_api.dll exit 1  # [win]
    - if not exist %SDRPLAY_PREFIX%\\lib\\sdrplay_api.lib exit 1  # [win]

    # verify that headers get installed
    - test -f $SDRPLAY_PREFIX/include/sdrplay_api.h  # [unix]
    - if not exist %SDRPLAY_PREFIX%\\include\\sdrplay_api.h exit 1  # [win]

about:
  home: https://www.sdrplay.com/api/
  license: LicenseRef-SDRplay-End-User-License-Agreement
  license_file: SDRplay_EULA
  summary: 'Script for downloading the SDRplay API binaries'
  description: >
    This package contains a conda activation script that will download the SDRplay API binaries to a local directory under a specified path.

    To use this package in a normal conda environment, do the following:

        export CONDA_BUILD_SDRPLAY_API=/opt

    (or use another suitable path instead of `/opt`).

    To use this package in a conda-build environment, add the following to the `conda_build_config.yaml` file in your user's HOME directory, the current working directory, or in the same folder as the recipe's `meta.yaml` file:

        CONDA_BUILD_SDRPLAY_API:
          - "/opt"

    (or use another suitable path instead of `/opt`).

    By setting this variable, you are agreeing to the terms and conditions of the SDRplay end user license agreement. For reference, this license is included in the package and installed to `$CONDA_PREFIX/share/doc/sdrplay_api/copyright`.

extra:
  recipe-maintainers:
    - ryanvolz
